### ISSUE TITLE
How do I use the spinner to switch languages?

### ISSUE THREAD

**Issue by harborbest** [metalurgus/LocaleText#1]
I now use the following code to set the language error, how to solve this problem?

 switch (position){
                           case 0:
                               LocaleText.setLocale(new Locale("en", "US"), getContext());
                               break;
                           case 1:
                               LocaleText.setLocale(new Locale("es", "ES"), getContext());
                               break;
                       }

Error message:
android.content.res.Resources$NotFoundException: String resource ID #0x0

**Comment by metalurgus** [comment]
you probably provided wrong ID (0 actually) as a string resource ID. Show full stacktrace and related piece of code
